### PR TITLE
Add session Id

### PR DESCRIPTION
**Pull request by remilemonnier**
Add Session Id value and session keys defined in config_dev inside the debug toolbar.

### CODE REVIEW

**Comment by benji07** [comment]
why don't display every key by default ?

**Comment by remilemonnier** [comment]
Because if you have a lot of keys, display will be unreadable.

**Comment by robertfausk** [comment]
Will there be any progress on this?

**Comment by remilemonnier** [comment]
Next progress is to merge it.
@robertfausk Did you test the feature?

**Pull request closed without merging**
